Warning  UpdateFailed  46s (x7 over 47s)  external-secrets  the desired SecretStore azure-kv is not ready
  Warning  UpdateFailed  4s (x7 over 46s)   external-secrets  keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=aee07df1-1c39-4195-835e-390813ad4daf;oid=a9b8bcc0-a4a6-428a-acdb-a6c60ea27c5e;iss=https://sts.windows.net/38b7fc89-dbe8-4ed1-a78b-39dfb6a217a8/' does not have secrets get permission on key vault 'EDDV-APP-EIKV01;location=canadaeast'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}


FROM docker.io/python:3.12.10-alpine3.21

RUN apk update && apk add --no-cache \
bash \
gcc \
musl-dev \
postgresql-dev \
libffi-dev \
openssl-dev \
build-base \
python3-dev \
py3-pip \
abseil-cpp-dev \
re2
   

# Install Python packages
RUN pip install --no-cache-dir \
psycopg2-binary \
pytz \
pybind11 \
apache-airflow

